// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/inference.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flat array of features: [seq_len * n_features] = [60 * 76] = 4560 floats.
	Features []float32 `protobuf:"fixed32,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	// Timestamp of the latest bar in microseconds since epoch.
	TimestampUs   int64 `protobuf:"varint,2,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetFeatures() []float32 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PredictRequest) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

type PredictResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Student-t mixture parameters (K=4 components).
	Pi    []float32 `protobuf:"fixed32,1,rep,packed,name=pi,proto3" json:"pi,omitempty"`
	Mu    []float32 `protobuf:"fixed32,2,rep,packed,name=mu,proto3" json:"mu,omitempty"`
	Sigma []float32 `protobuf:"fixed32,3,rep,packed,name=sigma,proto3" json:"sigma,omitempty"`
	Nu    []float32 `protobuf:"fixed32,4,rep,packed,name=nu,proto3" json:"nu,omitempty"`
	// Calibrated P(return > 0 in next 15 minutes).
	ProbUp float32 `protobuf:"fixed32,5,opt,name=prob_up,json=probUp,proto3" json:"prob_up,omitempty"`
	// XGBoost-derived features (fed back into feature vector for next bar).
	XgbProb        float32 `protobuf:"fixed32,6,opt,name=xgb_prob,json=xgbProb,proto3" json:"xgb_prob,omitempty"`
	XgbUncertainty float32 `protobuf:"fixed32,7,opt,name=xgb_uncertainty,json=xgbUncertainty,proto3" json:"xgb_uncertainty,omitempty"`
	BsImpliedProb  float32 `protobuf:"fixed32,8,opt,name=bs_implied_prob,json=bsImpliedProb,proto3" json:"bs_implied_prob,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetPi() []float32 {
	if x != nil {
		return x.Pi
	}
	return nil
}

func (x *PredictResponse) GetMu() []float32 {
	if x != nil {
		return x.Mu
	}
	return nil
}

func (x *PredictResponse) GetSigma() []float32 {
	if x != nil {
		return x.Sigma
	}
	return nil
}

func (x *PredictResponse) GetNu() []float32 {
	if x != nil {
		return x.Nu
	}
	return nil
}

func (x *PredictResponse) GetProbUp() float32 {
	if x != nil {
		return x.ProbUp
	}
	return 0
}

func (x *PredictResponse) GetXgbProb() float32 {
	if x != nil {
		return x.XgbProb
	}
	return 0
}

func (x *PredictResponse) GetXgbUncertainty() float32 {
	if x != nil {
		return x.XgbUncertainty
	}
	return 0
}

func (x *PredictResponse) GetBsImpliedProb() float32 {
	if x != nil {
		return x.BsImpliedProb
	}
	return 0
}

var File_proto_inference_proto protoreflect.FileDescriptor

const file_proto_inference_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inference.proto\x12\tinference\"O\n" +
	"\x0ePredictRequest\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\x02R\bfeatures\x12!\n" +
	"\ftimestamp_us\x18\x02 \x01(\x03R\vtimestampUs\"\xdc\x01\n" +
	"\x0fPredictResponse\x12\x0e\n" +
	"\x02pi\x18\x01 \x03(\x02R\x02pi\x12\x0e\n" +
	"\x02mu\x18\x02 \x03(\x02R\x02mu\x12\x14\n" +
	"\x05sigma\x18\x03 \x03(\x02R\x05sigma\x12\x0e\n" +
	"\x02nu\x18\x04 \x03(\x02R\x02nu\x12\x17\n" +
	"\aprob_up\x18\x05 \x01(\x02R\x06probUp\x12\x19\n" +
	"\bxgb_prob\x18\x06 \x01(\x02R\axgbProb\x12'\n" +
	"\x0fxgb_uncertainty\x18\a \x01(\x02R\x0exgbUncertainty\x12&\n" +
	"\x0fbs_implied_prob\x18\b \x01(\x02R\rbsImpliedProb2T\n" +
	"\x10InferenceService\x12@\n" +
	"\aPredict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponseB4Z2github.com/CalebCress/btc-options-pricing/go/protob\x06proto3"

var (
	file_proto_inference_proto_rawDescOnce sync.Once
	file_proto_inference_proto_rawDescData []byte
)

func file_proto_inference_proto_rawDescGZIP() []byte {
	file_proto_inference_proto_rawDescOnce.Do(func() {
		file_proto_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inference_proto_rawDesc), len(file_proto_inference_proto_rawDesc)))
	})
	return file_proto_inference_proto_rawDescData
}

var file_proto_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_inference_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: inference.PredictRequest
	(*PredictResponse)(nil), // 1: inference.PredictResponse
}
var file_proto_inference_proto_depIdxs = []int32{
	0, // 0: inference.InferenceService.Predict:input_type -> inference.PredictRequest
	1, // 1: inference.InferenceService.Predict:output_type -> inference.PredictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inference_proto_init() }
func file_proto_inference_proto_init() {
	if File_proto_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inference_proto_rawDesc), len(file_proto_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inference_proto_goTypes,
		DependencyIndexes: file_proto_inference_proto_depIdxs,
		MessageInfos:      file_proto_inference_proto_msgTypes,
	}.Build()
	File_proto_inference_proto = out.File
	file_proto_inference_proto_goTypes = nil
	file_proto_inference_proto_depIdxs = nil
}
