# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"8\n\x0ePredictRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\x12\x14\n\x0ctimestamp_us\x18\x02 \x01(\x03\"\x99\x01\n\x0fPredictResponse\x12\n\n\x02pi\x18\x01 \x03(\x02\x12\n\n\x02mu\x18\x02 \x03(\x02\x12\r\n\x05sigma\x18\x03 \x03(\x02\x12\n\n\x02nu\x18\x04 \x03(\x02\x12\x0f\n\x07prob_up\x18\x05 \x01(\x02\x12\x10\n\x08xgb_prob\x18\x06 \x01(\x02\x12\x17\n\x0fxgb_uncertainty\x18\x07 \x01(\x02\x12\x17\n\x0f\x62s_implied_prob\x18\x08 \x01(\x02\x32T\n\x10InferenceService\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponseB4Z2github.com/CalebCress/btc-options-pricing/go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/CalebCress/btc-options-pricing/go/proto'
  _globals['_PREDICTREQUEST']._serialized_start=30
  _globals['_PREDICTREQUEST']._serialized_end=86
  _globals['_PREDICTRESPONSE']._serialized_start=89
  _globals['_PREDICTRESPONSE']._serialized_end=242
  _globals['_INFERENCESERVICE']._serialized_start=244
  _globals['_INFERENCESERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
